// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwkLlG7mSz0LkQXsR9S619-6rxizfL-NI',
    appId: '1:58001007583:web:cece30c078074d69ac9a6a',
    messagingSenderId: '58001007583',
    projectId: 'fastx-4f421',
    authDomain: 'fastx-4f421.firebaseapp.com',
    storageBucket: 'fastx-4f421.appspot.com',
    measurementId: 'G-G97W3HJVK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTH7k58IhNJRckHPz3eBHQf11L2Oa1j5M',
    appId: '1:944429639165:android:3c801f4df5a58f2174e594',
    messagingSenderId: '944429639165',
    projectId: 'kipgra-472312',
    storageBucket: 'kipgra-472312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttz-e6K-rcD7-x4zlb4D4Ojk_0USzoxM',
    appId: '1:58001007583:ios:1c7a2d6ce00c1f2cac9a6a',
    messagingSenderId: '58001007583',
    projectId: 'fastx-4f421',
    storageBucket: 'fastx-4f421.appspot.com',
    iosBundleId: 'com.example.fastxDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCttz-e6K-rcD7-x4zlb4D4Ojk_0USzoxM',
    appId: '1:58001007583:ios:1c7a2d6ce00c1f2cac9a6a',
    messagingSenderId: '58001007583',
    projectId: 'fastx-4f421',
    storageBucket: 'fastx-4f421.appspot.com',
    iosBundleId: 'com.example.fastxDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwkLlG7mSz0LkQXsR9S619-6rxizfL-NI',
    appId: '1:58001007583:web:a06908f0aa586628ac9a6a',
    messagingSenderId: '58001007583',
    projectId: 'fastx-4f421',
    authDomain: 'fastx-4f421.firebaseapp.com',
    storageBucket: 'fastx-4f421.appspot.com',
    measurementId: 'G-T1VBJ3XRH9',
  );
}
